openapi: 3.0.0
info:
  title: ArgentBank - Transaction API
  description: ''
  version: '1.0.0'
servers:
  - url: http://localhost:3001/api/v1
    description: Local server
paths:
  /account/{accountId}/transactions:
    get:
      tags:
        - Account
      summary: Gets an array of transactions of specified bank account ID.
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: integer
            minimum: 1
          description: The ID of the account to return.
      responses:
        '200':
          description: transactions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: 200
                message: "Success"
                body:
                  - id: 11198772
                    date: "2024-07-10T16:00:56.382Z"
                    amount: 
                      value: "10.99"
                      currency: "USD"
                  - id: 40055552
                    date: "2024-03-10T12:32:56.382Z"
                    amount: 
                      value: "40.00"
                      currency: "USD"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound' 
        '500':
          $ref: '#/components/responses/InternalServerError' 
          
  /transaction/{transactionId}:
    get:
      tags:
        - Transaction
      summary: Gets an existing transaction with the specified ID.
      parameters:
        - in: path
          name: transactionId
          required: true
          schema:
            type: integer
            minimum: 1
          description: The ID of the transaction to return.
      responses:
        '200':
          description: transaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: 200
                message: "Success"
                body:
                  id: 40055552
                  date: "2024-03-10T12:32:56.382Z"
                  amount: 
                    value: "40.00"
                    currency: "USD"
                  type: "Electronic"
                  category: "Food"
                  notes: "Lorem ispum sit amet dolor"
        '401':
          $ref: '#/components/responses/Unauthorized'  
        '404':
          $ref: '#/components/responses/NotFound' 
        '500':
          $ref: '#/components/responses/InternalServerError' 
    patch:
      tags:
        - Transaction
      summary: Updates an existing transaction with the specified ID.
      parameters:
        - in: path
          name: transactionId
          required: true
          schema:
            type: integer
            minimum: 1
          description: The ID of the transaction to return.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          description: transaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: 200
                message: "Successfull update"
        '400':
          $ref: '#/components/responses/BadRequest' 
        '401':
          $ref: '#/components/responses/Unauthorized' 
        '404':
          $ref: '#/components/responses/NotFound' 
        '500':
          $ref: '#/components/responses/InternalServerError'
security:
  - bearerAuth: [] 
components:
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
          example: 
            status: 400
            message: "Bad Request"
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
          example: 
            status: 401
            message: "Unauthorized"
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
          example: 
            status: 404
            message: "Not Found"
    InternalServerError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
          example: 
            status: 500
            message: "Internal Server Error"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Response:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        body:
          type: object
      required:
        - status
        - message
    Transaction:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
          example: 11198772
        date:
          type: string
          format: date-time
          readOnly: true
        amount:
          type: object
          readOnly: true
          properties:
            currency:
              type: string
              example: "USD"
            value:
              type: string
              example: "31.50"
        type:
          type: string
          readOnly: true
          example: 'Electronic'
        category:
          type: string
          example: 'Food'
        notes:
          type: string
          example: 'Lorem ispum sit amet dolor'
        